pipeline {
    agent any

    parameters {
        string(
            name: 'BRANCH_NAME',
            defaultValue: '',
            description: 'Git branch to build'
        )
    }

    tools {
        nodejs 'node-25' // Name of NodeJS installation in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.BRANCH_NAME}", url: 'https://github.com/trackme-app/TrackMe-Edu.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install --workspaces'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}
