pipeline {
    agent {
        docker {
            image 'node:25-bullseye' // Debian-based Node.js image
            args '-u root'            // Run container as root so you can install packages
        }
    }

    environment {
        NODE_ENV = 'production'
    }

    stages {
        stage('Setup System Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y libatomic1
                '''
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/trackme-app/TrackMe-Edu.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}
